spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
mybatis:
  mapper-locations: classpath*:com/example/webdemo/dao/mapper/*.xml
server:
  port: 9090
mq:
  namesrvAddr: 127.0.0.1:9876
  producerEnable: false
  consumerEnable: false
logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug